# Generated by Django 3.2.18 on 2023-03-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0002_tb_master_answer_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tb_master_kategori_answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_master_answer', models.IntegerField(blank=True, default=None, null=True)),
                ('kategori_answer', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'db_table': 'tb_master_kategori_answer',
            },
        ),
        migrations.RemoveField(
            model_name='tb_master_answer',
            name='desc',
        ),
    ]
