# Generated by Django 3.2.18 on 2023-03-27 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0003_auto_20230327_2309'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tb_master_answer',
            table='tb_master_answer',
        ),
    ]
