# Generated by Django 4.1.7 on 2023-04-14 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0005_auto_20230327_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_master_answer',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tb_master_answer',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tb_master_kategori_answer',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tb_master_kategori_answer',
            name='id_master_answer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='kuesioner.tb_master_answer'),
        ),
        migrations.AlterField(
            model_name='tb_master_kategori_answer',
            name='kategori_answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tb_master_kategori_soal',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tb_master_kategori_soal',
            name='id_kategori',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='kuesioner.tb_master_kategori_answer'),
        ),
        migrations.AlterField(
            model_name='tb_soal_kepentingan',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tb_soal_kepentingan',
            name='id_kategori',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='kuesioner.tb_master_kategori_soal'),
        ),
        migrations.AlterField(
            model_name='tb_soal_kepentingan',
            name='id_master_answer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='kuesioner.tb_master_answer'),
        ),
        migrations.AlterField(
            model_name='tb_soal_kepuasan',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tb_soal_kepuasan',
            name='id_kategori',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='kuesioner.tb_master_kategori_soal'),
        ),
        migrations.AlterField(
            model_name='tb_soal_kepuasan',
            name='id_master_answer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='kuesioner.tb_master_answer'),
        ),
        migrations.AlterField(
            model_name='tb_soal_kepuasan_umum',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tb_soal_kepuasan_umum',
            name='id_master_answer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='kuesioner.tb_master_answer'),
        ),
    ]
