# Generated by Django 4.1.7 on 2023-04-14 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0006_alter_tb_master_answer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tb_answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200)),
                ('score', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'db_table': 'Tb_answer',
            },
        ),
        migrations.CreateModel(
            name='Tb_kategori_soal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori_soal', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
            ],
            options={
                'db_table': 'Tb_kategori_soal',
            },
        ),
        migrations.CreateModel(
            name='Tb_test_kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori_answer', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
            ],
            options={
                'db_table': 'Tb_test_kategori',
            },
        ),
        migrations.RemoveField(
            model_name='tb_master_kategori_answer',
            name='id_master_answer',
        ),
        migrations.RemoveField(
            model_name='tb_master_kategori_soal',
            name='id_kategori',
        ),
        migrations.RemoveField(
            model_name='tb_soal_kepentingan',
            name='id_master_answer',
        ),
        migrations.RemoveField(
            model_name='tb_soal_kepuasan',
            name='id_master_answer',
        ),
        migrations.RemoveField(
            model_name='tb_soal_kepuasan_umum',
            name='id_master_answer',
        ),
        migrations.AlterField(
            model_name='tb_soal_kepentingan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tb_soal_kepuasan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tb_soal_kepuasan_umum',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Tb_master_answer',
        ),
        migrations.DeleteModel(
            name='Tb_master_kategori_answer',
        ),
        migrations.AddField(
            model_name='tb_kategori_soal',
            name='id_kategori',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='kuesioner.tb_test_kategori'),
        ),
        migrations.AddField(
            model_name='tb_answer',
            name='id_test_kategori',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='kuesioner.tb_test_kategori'),
        ),
        migrations.AlterField(
            model_name='tb_soal_kepentingan',
            name='id_kategori',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='kuesioner.tb_kategori_soal'),
        ),
        migrations.AlterField(
            model_name='tb_soal_kepuasan',
            name='id_kategori',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='kuesioner.tb_kategori_soal'),
        ),
        migrations.DeleteModel(
            name='Tb_master_kategori_soal',
        ),
    ]
