# Generated by Django 4.1.7 on 2023-04-15 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0008_rename_id_kategori_tb_soal_kepentingan_id_kat_soal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_soal_kepuasan_umum',
            name='id_kat_soal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='kuesioner.tb_test_kategori'),
        ),
    ]
