# Generated by Django 4.1.7 on 2023-04-15 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0009_tb_soal_kepuasan_umum_id_kat_soal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tb_soal_kepuasan_umum',
            old_name='id_kat_soal',
            new_name='id_kategori',
        ),
    ]
