# Generated by Django 4.1.7 on 2023-05-06 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0013_user_userdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
