# Generated by Django 4.1.7 on 2023-05-06 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0015_userprofileinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
