# Generated by Django 4.1.7 on 2023-05-13 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0017_m_location_m_position'),
    ]

    operations = [
        migrations.DeleteModel(
            name='m_position',
        ),
    ]
