# Generated by Django 4.1.7 on 2023-05-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0018_delete_m_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='m_position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('staff', 'Staff'), ('team_leader', 'Team Leader'), ('supervisor', 'Supervisor'), ('manager', 'Manager'), ('director', 'Director')], max_length=50)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
            ],
            options={
                'db_table': 'm_position',
            },
        ),
    ]
