# Generated by Django 4.1.7 on 2023-05-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0022_userdetail_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='user',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='username',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
