# Generated by Django 4.1.7 on 2023-05-13 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0024_remove_userdetail_email_remove_userdetail_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
