# Generated by Django 4.1.7 on 2023-05-20 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0021_user_data'),
        ('kuesioner', '0027_remove_userdetail_email_remove_userdetail_first_name_and_more'),
    ]

    operations = [
    ]
