# Generated by Django 4.1.7 on 2023-05-20 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0028_merge_20230520_1307'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
