# Generated by Django 4.1.7 on 2023-05-20 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0029_delete_userdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='id_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.m_location'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='id_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.m_position'),
        ),
    ]
