# Generated by Django 4.1.7 on 2023-05-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0030_alter_user_data_id_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
