# Generated by Django 4.1.7 on 2023-05-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0031_alter_user_data_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
