# Generated by Django 4.1.7 on 2023-06-07 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0035_userresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kuesioner.tb_answer'),
        ),
    ]
