# Generated by Django 4.1.7 on 2023-06-07 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kuesioner', '0036_alter_userresponse_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResponse1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kuesioner.tb_answer')),
                ('kat_soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kuesioner.tb_kategori_soal')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kuesioner.tb_soal_kepentingan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserResponse1',
            },
        ),
    ]
