# Generated by Django 4.1.7 on 2023-06-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0037_userresponse1'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userresponse1',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
