# Generated by Django 4.1.7 on 2023-06-16 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0044_m_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='m_education',
            old_name='pendidikan',
            new_name='education',
        ),
    ]
