# Generated by Django 4.1.7 on 2023-06-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0045_rename_pendidikan_m_education_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='m_age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
            ],
            options={
                'db_table': 'm_age',
            },
        ),
    ]
