# Generated by Django 4.1.7 on 2023-06-16 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0046_m_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='age',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.m_age'),
        ),
        migrations.AddField(
            model_name='user_data',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.m_education'),
        ),
    ]
