# Generated by Django 4.1.7 on 2023-06-17 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0047_user_data_age_user_data_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='m_korsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('korsa', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
            ],
            options={
                'db_table': 'm_korsa',
            },
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='age',
        ),
        migrations.DeleteModel(
            name='m_age',
        ),
        migrations.AddField(
            model_name='user_data',
            name='korsa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.m_korsa'),
        ),
    ]
