# Generated by Django 4.1.7 on 2023-06-17 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0048_m_korsa_remove_user_data_age_delete_m_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='m_jenis_jabatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_jabatan', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
            ],
            options={
                'db_table': 'm_jenis_jabatan',
            },
        ),
        migrations.AddField(
            model_name='user_data',
            name='jenis_jabatan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.m_jenis_jabatan'),
        ),
    ]
