# Generated by Django 4.1.7 on 2023-06-18 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0049_m_jenis_jabatan_user_data_jenis_jabatan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_data',
            old_name='id_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='user_data',
            old_name='id_position',
            new_name='position',
        ),
    ]
