# Generated by Django 4.1.7 on 2023-06-26 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0050_rename_id_location_user_data_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='count_user_umum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_count', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kuesioner.tb_soal_kepuasan_umum')),
            ],
        ),
    ]
