# Generated by Django 4.1.7 on 2023-06-26 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0051_count_user_umum'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='count_user_umum',
            table='count_user_umum',
        ),
    ]
