# Generated by Django 4.1.7 on 2023-07-03 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0053_count_user_umum_total_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='count_user_kepentingan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_count', models.IntegerField()),
                ('total_score', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kuesioner.tb_soal_kepentingan')),
            ],
            options={
                'db_table': 'count_user_kepentingan',
            },
        ),
    ]
