# Generated by Django 4.2.3 on 2023-07-15 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0055_count_user_kepuasan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tb_kategori_soal',
            old_name='kategori_soal',
            new_name='kategori_dimensi',
        ),
        migrations.RenameField(
            model_name='tb_kategori_soal',
            old_name='test_kategori',
            new_name='test',
        ),
    ]
