# Generated by Django 4.2.3 on 2023-07-15 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0056_rename_kategori_soal_tb_kategori_soal_kategori_dimensi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tb_soal_kepentingan',
            old_name='kat_soal',
            new_name='kat',
        ),
    ]
