# Generated by Django 4.2.3 on 2023-07-15 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0057_rename_kat_soal_tb_soal_kepentingan_kat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tb_soal_kepentingan',
            old_name='kat',
            new_name='kat_soal',
        ),
    ]
