# Generated by Django 4.2.3 on 2023-07-15 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0060_rename_kat_soal_tb_soal_kepentingan_kat_soals_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tb_soal_kepentingan',
            old_name='kat_soals',
            new_name='kat_soal',
        ),
        migrations.RenameField(
            model_name='tb_soal_kepuasan',
            old_name='kat_soals',
            new_name='kat_soal',
        ),
    ]
