# Generated by Django 4.2.3 on 2023-07-15 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0061_rename_kat_soals_tb_soal_kepentingan_kat_soal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tb_soal_kepentingan',
            old_name='test_kategori',
            new_name='test',
        ),
        migrations.RenameField(
            model_name='tb_soal_kepuasan',
            old_name='test_kategori',
            new_name='test',
        ),
    ]
