# Generated by Django 4.2.3 on 2023-07-15 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0062_rename_test_kategori_tb_soal_kepentingan_test_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tb_kategori_soal',
            old_name='test_kategori',
            new_name='test',
        ),
        migrations.RenameField(
            model_name='tb_soal_kepuasan_umum',
            old_name='test_kategori',
            new_name='test',
        ),
    ]
