# Generated by Django 4.2.3 on 2023-07-15 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0063_rename_test_kategori_tb_kategori_soal_test_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tb_kategori_soal',
            old_name='kategori_soal',
            new_name='kategori_dimensi',
        ),
    ]
