# Generated by Django 4.2.3 on 2023-07-15 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0064_rename_kategori_soal_tb_kategori_soal_kategori_dimensi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tb_kategori_soal',
            old_name='kategori_dimensi',
            new_name='kat_dimensi',
        ),
    ]
