# Generated by Django 4.2.3 on 2023-07-15 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0065_rename_kategori_dimensi_tb_kategori_soal_kat_dimensi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tb_soal_kepentingan',
            old_name='kat_soal',
            new_name='dimensi',
        ),
        migrations.RenameField(
            model_name='tb_soal_kepuasan',
            old_name='kat_soal',
            new_name='dimensi',
        ),
    ]
