# Generated by Django 4.2.3 on 2023-07-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0069_tb_score_lvl_delete_totalscorelvlkepuasan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tb_score_lvl',
            old_name='total_score',
            new_name='total_score_lvl_kepentingan',
        ),
        migrations.AddField(
            model_name='tb_score_lvl',
            name='total_score_lvl_kepuasan',
            field=models.IntegerField(default=0),
        ),
    ]
