# Generated by Django 4.2.3 on 2023-07-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0073_rename_total_score_lvl_kepentingan_tb_score_lvl_total_score_lvl_kepuasan'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_score_lvl',
            name='total_score_lvl_kepentingan',
            field=models.IntegerField(default=0),
        ),
    ]
