# Generated by Django 4.2.3 on 2023-07-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0074_tb_score_lvl_total_score_lvl_kepentingan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count_user_kepentingan',
            name='user_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='count_user_kepuasan',
            name='user_count',
            field=models.IntegerField(default=0),
        ),
    ]
