# Generated by Django 4.2.3 on 2023-07-28 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0077_rename_saran_dan_komentar_usercomment_komentar_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usercomment',
            table='user_comment',
        ),
    ]
