# Generated by Django 4.2.3 on 2023-07-28 11:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0078_alter_usercomment_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomment',
            name='sentiment',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usercomment',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
